title: "Series-02-Rstudio : corelations and statistical test"
author: "Matys PRÉCLOUX"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output:
  html_document:
    df_print: paged
    code_folding: hide
    toc: false
    number_sections: true
---

# Correlations and linear regression
In this series of exercises, you will explore correlations and linear regression, using a dataset from a real experiment.

## The problem
You want to know if there is a relationship between the nonuse of the proximal part of the upper limb (PANU) and the nonuse of the shoulder (SANU) or the elbow (EENU).

## The data
As you will see, the data is far from perfect, but this is the reality of experimental data, especially in the case of clinical data.

Download the file NonUse.csv from the course Moodle.

This file contains measures of upper extremity nonuse:

    PANU: Proximal Arm Non Use
    SANU: Shoulder Antepulsion Non Use
    EENU: Elbow Extension Non Use

In your notebook, make a clear description of the experiment, the variables and the data. Do not forget to give the units of each variable, and the range of possible values.

## Corelation analysis
Below are some questions to guide your analysis.

- Is PANU correlated with SANU and/or EENU?

- Visualize the PANU-SANU relationship (and the PANU-EENU relationship)

- Perform a linear regression for PANU-SANU (and for PANU-EENU)

- Give the regression equations: PANU = a * SANU + b and PANU = a * EENU + b
- Summarize your results as you would do in your master’s thesis report, or as in a scientific article (e.g., What sentence will you write in the article explaining your result?).
- What are the limits of your analysis?